name: Deploy Helm Chart

on:
  push:
    branches:
      - dev-branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Helm chart
        run: helm upgrade my-release-namespace my-helm-chart --namespace my-namespace
