name: Deploy Helm Chart

on:
  push:
    branches:
      - dev-branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Deploy Helm chart
        run: helm install my-release-namespace /Users/betrandmutagha/my-helm-chart --namespace dev-namespace
